package projeto2;

import javax.swing.JOptionPane;

public class jfCadPaciente_1 extends javax.swing.JFrame {
    
    /** Creates new form jfPaciente */
    public jfCadPaciente_1() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtNomePaciente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jbCadastrarPaciente = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtNascimentoPaciente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtTelefonePaciente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtEnderecoPaciente = new javax.swing.JTextField();
        jtNumeroPaciente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtEmailPaciente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtProfissaoPaciente = new javax.swing.JTextField();
        jtDddPaciente = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jtBairroPaciente = new javax.swing.JTextField();
        jtCidadePaciente = new javax.swing.JTextField();
        cbEstadoPaciente = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Paciente");
        setResizable(false);

        jtNomePaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNomePacienteActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome do Paciente:");

        jbCadastrarPaciente.setLabel("Cadastrar");
        jbCadastrarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarPacienteActionPerformed(evt);
            }
        });

        jToggleButton2.setLabel("Cancelar");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(":: Cadastro de Paciente ::");

        jLabel4.setText("Data Nascimento:");

        jtNascimentoPaciente.setName("jtNascimentoPaciente"); // NOI18N
        jtNascimentoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNascimentoPacienteActionPerformed(evt);
            }
        });

        jLabel3.setText("Telefone:");

        jLabel5.setText("Endereço:");

        jLabel7.setText("E-Mail:");

        jLabel8.setText("Profissão:");

        jLabel9.setText("-");

        jLabel6.setText("Bairro:");

        jLabel10.setText("Cidade:");

        jLabel11.setText("Estado:");

        jtBairroPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtBairroPacienteActionPerformed(evt);
            }
        });

        cbEstadoPaciente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RO", "RR", "RS", "SC", "SE", "SP", "TO" }));
        cbEstadoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEstadoPacienteActionPerformed(evt);
            }
        });

        jLabel12.setText("Número:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtNomePaciente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(87, 87, 87)
                                                .addComponent(jLabel7))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jtDddPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jtTelefonePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jtEmailPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addComponent(jLabel2))
                                .addGap(10, 10, 10)))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtNascimentoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jtProfissaoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(49, 49, 49))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jtCidadePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(cbEstadoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jtEnderecoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtNumeroPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jtBairroPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(212, Short.MAX_VALUE)
                .addComponent(jbCadastrarPaciente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton2)
                .addGap(225, 225, 225))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtNomePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtNascimentoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(jtDddPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jtTelefonePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtEmailPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtProfissaoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtEnderecoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtNumeroPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtBairroPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtCidadePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbEstadoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton2)
                    .addComponent(jbCadastrarPaciente))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String NomePaciente, NascimentoPaciente, DDDPaciente, TelefonePaciente;
    public String EnderecoPaciente, NumeroPaciente, EmailPaciente, ProfissaoPaciente;
    public String BairroPaciente, CidadePaciente, EstadoPaciente;

    private String CodigoPaciente;
    private int nCodigoPaciente;

          


    private void jbCadastrarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarPacienteActionPerformed

        //Guarda os valores dos campos áreas de texto em uma variável
        NomePaciente       = jtNomePaciente.getText();
        NascimentoPaciente = jtNascimentoPaciente.getText();
        DDDPaciente        = jtDddPaciente.getText();
        TelefonePaciente   = jtTelefonePaciente.getText();
        EmailPaciente      = jtEmailPaciente.getText();
        ProfissaoPaciente  = jtProfissaoPaciente.getText();
        EnderecoPaciente   = jtEnderecoPaciente.getText();
        NumeroPaciente     = jtNumeroPaciente.getText();
        BairroPaciente     = jtBairroPaciente.getText();
        CidadePaciente     = jtCidadePaciente.getText();
        EstadoPaciente = (String) cbEstadoPaciente.getSelectedItem();
        
        if (NomePaciente.equals("")) {
            JOptionPane.showMessageDialog(null, "Favor preencher o nome do paciente!");
        }
        else if (NascimentoPaciente.equals("")) {
            JOptionPane.showMessageDialog(null, "Favor preencher a data de nascimento!");
        }
        else if (DDDPaciente.equals("")) {
            JOptionPane.showMessageDialog(null, "Favor preencher o número DDD!");
        }
        else if (TelefonePaciente.equals("")) {
            JOptionPane.showMessageDialog(null, "Favor preencher o telefone!");
        }
        else if (EmailPaciente.equals("")) {
            JOptionPane.showMessageDialog(null, "Favor preencher o e-mail!");
        }
        else if (ProfissaoPaciente.equals("")) {
            JOptionPane.showMessageDialog(null, "Favor preencher a profissão!");
        }
        else if (EnderecoPaciente.equals("")) {
            JOptionPane.showMessageDialog(null, "Favor preencher o endereço!");
        }
        else if (NumeroPaciente.equals("")) {
            JOptionPane.showMessageDialog(null, "Favor preencher o número!");
        }
        else if (BairroPaciente.equals("")) {
            JOptionPane.showMessageDialog(null, "Favor preencher o bairro!");
        }
        else if (CidadePaciente.equals("")) {
            JOptionPane.showMessageDialog(null, "Favor preencher a cidade!");
        }
        else if (EstadoPaciente.equals("Selecione")) {
            JOptionPane.showMessageDialog(null, "Favor preencher o estado!");
        }
        else{

            //Verifica qual é o próximo código
            clCodProximoPaciente CodProximoPaciente = new clCodProximoPaciente();
            CodigoPaciente = CodProximoPaciente.paciente();

            if (CodigoPaciente ==  null){
            CodigoPaciente = "1";            
            }
            else {
                nCodigoPaciente = Integer.parseInt(CodigoPaciente) + 1;
            }


            JOptionPane.showMessageDialog(null, nCodigoPaciente);

  
            clArquivoPaciente _file = new clArquivoPaciente("Paciente.txt");
            _file.openFile();
            _file.writeInFile(nCodigoPaciente + "\t" + NomePaciente + "\t" + NascimentoPaciente + "\t" + DDDPaciente + "\t" + TelefonePaciente + "\t" + EmailPaciente + "\t" + ProfissaoPaciente + "\t" + EnderecoPaciente + "\t" + NumeroPaciente + "\t" + BairroPaciente + "\t" + CidadePaciente + "\t" + EstadoPaciente + "\r\n");
            _file.closeFile();


            jtNomePaciente.setText("");
            jtNascimentoPaciente.setText("");
            jtDddPaciente.setText("");
            jtTelefonePaciente.setText("");
            jtEnderecoPaciente.setText("");
            jtBairroPaciente.setText("");
            jtCidadePaciente.setText("");
            jtNumeroPaciente.setText("");
            jtEmailPaciente.setText("");
            jtProfissaoPaciente.setText("");


        }

        
}//GEN-LAST:event_jbCadastrarPacienteActionPerformed

    private void jtNomePacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNomePacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNomePacienteActionPerformed

    private void jtNascimentoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNascimentoPacienteActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jtNascimentoPacienteActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
       this.setVisible(false);
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jtBairroPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtBairroPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtBairroPacienteActionPerformed

    private void cbEstadoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEstadoPacienteActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_cbEstadoPacienteActionPerformed

    /**
     @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfCadPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbEstadoPaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jbCadastrarPaciente;
    private javax.swing.JTextField jtBairroPaciente;
    private javax.swing.JTextField jtCidadePaciente;
    private javax.swing.JTextField jtDddPaciente;
    private javax.swing.JTextField jtEmailPaciente;
    private javax.swing.JTextField jtEnderecoPaciente;
    private javax.swing.JTextField jtNascimentoPaciente;
    private javax.swing.JTextField jtNomePaciente;
    private javax.swing.JTextField jtNumeroPaciente;
    private javax.swing.JTextField jtProfissaoPaciente;
    private javax.swing.JTextField jtTelefonePaciente;
    // End of variables declaration//GEN-END:variables
}
