package projeto2;

import javax.swing.JOptionPane;

public class jfCadMedico extends javax.swing.JFrame {

    /** Creates new form clCadMedico */
    public jfCadMedico() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtNomeMedico = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtDddMedico = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtTelefoneMedico = new javax.swing.JTextField();
        jtEmailMedico = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtNascimentoMedico = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtCRMMedico = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtCidadeMedico = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cbEstadoMedico = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jtEnderecoMedico = new javax.swing.JTextField();
        jtNumeroMedico = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtBairroMedico = new javax.swing.JTextField();
        jbCadastrarMedico = new javax.swing.JToggleButton();
        jbCancelarMedico = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Médicos");

        jLabel1.setText("Nome do Médico");

        jtNomeMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNomeMedicoActionPerformed(evt);
            }
        });

        jLabel3.setText("Telefone:");

        jLabel7.setText("E-Mail:");

        jLabel9.setText("-");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(":: Cadastro de Médico ::");

        jtNascimentoMedico.setName("jtNascimentoMedico"); // NOI18N
        jtNascimentoMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNascimentoMedicoActionPerformed(evt);
            }
        });

        jLabel8.setText("CRM:");

        jLabel4.setText("Data Nascimento:");

        jLabel10.setText("Cidade:");

        jLabel11.setText("Estado:");

        cbEstadoMedico.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RO", "RR", "RS", "SC", "SE", "SP", "TO" }));
        cbEstadoMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEstadoMedicoActionPerformed(evt);
            }
        });

        jLabel5.setText("Endereço:");

        jLabel12.setText("Número:");

        jLabel6.setText("Bairro:");

        jtBairroMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtBairroMedicoActionPerformed(evt);
            }
        });

        jbCadastrarMedico.setLabel("Cadastrar");
        jbCadastrarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarMedicoActionPerformed(evt);
            }
        });

        jbCancelarMedico.setLabel("Cancelar");
        jbCancelarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarMedicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtNomeMedico, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(87, 87, 87)
                                                .addComponent(jLabel7))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jtDddMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jtTelefoneMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jtEmailMedico, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addComponent(jLabel2))
                                .addGap(10, 10, 10)))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtNascimentoMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel4)
                            .addComponent(jtCRMMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(86, 86, 86))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jtCidadeMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(cbEstadoMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jtEnderecoMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtNumeroMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jtBairroMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(178, Short.MAX_VALUE)
                .addComponent(jbCadastrarMedico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbCancelarMedico)
                .addGap(225, 225, 225))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtNomeMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtNascimentoMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(jtDddMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jtTelefoneMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtEmailMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtCRMMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtEnderecoMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtNumeroMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtBairroMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtCidadeMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbEstadoMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCancelarMedico)
                    .addComponent(jbCadastrarMedico))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtNomeMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNomeMedicoActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jtNomeMedicoActionPerformed

    private void jtNascimentoMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNascimentoMedicoActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jtNascimentoMedicoActionPerformed

    private void cbEstadoMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEstadoMedicoActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_cbEstadoMedicoActionPerformed

    private void jtBairroMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtBairroMedicoActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jtBairroMedicoActionPerformed

    private void jbCadastrarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarMedicoActionPerformed
        //Guarda os valores dos campos áreas de texto em uma variável
        String NomeMedico = jtNomeMedico.getText();
        String NascimentoMedico = jtNascimentoMedico.getText();
        String DDDMedico = jtDddMedico.getText();
        String TelefoneMedico = jtTelefoneMedico.getText();
        String EmailMedico = jtEmailMedico.getText();
        String CRMMedico = jtCRMMedico.getText();
        String EnderecoMedico = jtEnderecoMedico.getText();
        String NumeroMedico = jtNumeroMedico.getText();
        String BairroMedico = jtBairroMedico.getText();
        String CidadeMedico = jtCidadeMedico.getText();
        String EstadoMedico = (String) cbEstadoMedico.getSelectedItem();
        Object nCodigoMedico = null;
        String CodigoMedico;

        if (NomeMedico.equals("")) {
            JOptionPane.showMessageDialog(null, "Favor preencher o nome do médico!");
        } else if (NascimentoMedico.equals("")) {
            JOptionPane.showMessageDialog(null, "Favor preencher a data de nascimento!");
        } else if (DDDMedico.equals("")) {
            JOptionPane.showMessageDialog(null, "Favor preencher o número DDD!");
        } else if (TelefoneMedico.equals("")) {
            JOptionPane.showMessageDialog(null, "Favor preencher o telefone!");
        } else if (EmailMedico.equals("")) {
            JOptionPane.showMessageDialog(null, "Favor preencher o e-mail!");
        } else if (CRMMedico.equals("")) {
            JOptionPane.showMessageDialog(null, "Favor preencher a profissão!");
        } else if (EnderecoMedico.equals("")) {
            JOptionPane.showMessageDialog(null, "Favor preencher o endereço!");
        } else if (NumeroMedico.equals("")) {
            JOptionPane.showMessageDialog(null, "Favor preencher o número!");
        } else if (BairroMedico.equals("")) {
            JOptionPane.showMessageDialog(null, "Favor preencher o bairro!");
        } else if (CidadeMedico.equals("")) {
            JOptionPane.showMessageDialog(null, "Favor preencher a cidade!");
        } else if (EstadoMedico.equals("Selecione")) {
            JOptionPane.showMessageDialog(null, "Favor preencher o estado!");
        } else{

            //Verifica qual é o próximo código
            clCodProximoMedico CodProximoMedico = new clCodProximoMedico();
            CodigoMedico = CodProximoMedico.medico();

            if (CodigoMedico ==  null){
                CodigoMedico = "1";
            } else {
                nCodigoMedico = Integer.parseInt(CodigoMedico) + 1;
            }

            clArquivoMedico _file = new clArquivoMedico("Medico.txt");
            _file.openFile();
            _file.writeInFile(nCodigoMedico + "\t" + NomeMedico + "\t" + NascimentoMedico + "\t" + DDDMedico + "\t" + TelefoneMedico + "\t" + EmailMedico + "\t" + CRMMedico + "\t" + EnderecoMedico + "\t" + NumeroMedico + "\t" + BairroMedico + "\t" + CidadeMedico + "\t" + EstadoMedico + "\r\n");
            _file.closeFile();

            jtNomeMedico.setText("");
            jtNascimentoMedico.setText("");
            jtDddMedico.setText("");
            jtTelefoneMedico.setText("");
            jtEnderecoMedico.setText("");
            jtBairroMedico.setText("");
            jtCidadeMedico.setText("");
            jtNumeroMedico.setText("");
            jtEmailMedico.setText("");
            jtCRMMedico.setText("");


        }


}//GEN-LAST:event_jbCadastrarMedicoActionPerformed

    private void jbCancelarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarMedicoActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
}//GEN-LAST:event_jbCancelarMedicoActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfCadMedico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbEstadoMedico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JToggleButton jbCadastrarMedico;
    private javax.swing.JToggleButton jbCancelarMedico;
    private javax.swing.JTextField jtBairroMedico;
    private javax.swing.JTextField jtCRMMedico;
    private javax.swing.JTextField jtCidadeMedico;
    private javax.swing.JTextField jtDddMedico;
    private javax.swing.JTextField jtEmailMedico;
    private javax.swing.JTextField jtEnderecoMedico;
    private javax.swing.JTextField jtNascimentoMedico;
    private javax.swing.JTextField jtNomeMedico;
    private javax.swing.JTextField jtNumeroMedico;
    private javax.swing.JTextField jtTelefoneMedico;
    // End of variables declaration//GEN-END:variables

}
