package projeto2;

import javax.swing.JOptionPane;

public class jfCadExame_1 extends javax.swing.JFrame {
    private String CodigoExame;


    /** Creates new form jfCadExame */
    public jfCadExame_1() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbCadastrarSintoma = new javax.swing.JButton();
        jbCancelarSintoma = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtDescricaoExame = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtRequisitoExame = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Exames");

        jbCadastrarSintoma.setText("Cadastrar");
        jbCadastrarSintoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarSintomaActionPerformed(evt);
            }
        });

        jbCancelarSintoma.setText("Cancelar");
        jbCancelarSintoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarSintomaActionPerformed(evt);
            }
        });

        jLabel1.setText("Descrição:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(":: Cadastro de Exames ::");

        jtDescricaoExame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtDescricaoExameActionPerformed(evt);
            }
        });

        jLabel3.setText("Requisitos:");

        jtRequisitoExame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtRequisitoExameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jtDescricaoExame, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jtRequisitoExame, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jbCadastrarSintoma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbCancelarSintoma)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtDescricaoExame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtRequisitoExame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCadastrarSintoma)
                    .addComponent(jbCancelarSintoma))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCadastrarSintomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarSintomaActionPerformed

        String DescricaoExame = jtDescricaoExame.getText();
        String RequisitoExame = jtRequisitoExame.getText();
        int nCodigoExame = 0;


        if (DescricaoExame.equals("")) {
            JOptionPane.showMessageDialog(null, "Favor preencher a descrição do exame!");
        }
        else if (RequisitoExame.equals("")) {
            JOptionPane.showMessageDialog(null, "Favor preencher os requisitos para o exame!");
        } 
        else {

        //Verifica qual é o próximo código
        clCodProximoExame CodProximoExame = new clCodProximoExame();
        CodigoExame = CodProximoExame.exame();
            
        if (CodigoExame ==  null){
             CodigoExame = "1";
        }
        else {
           nCodigoExame = Integer.parseInt(CodigoExame) + 1;
        }

        clArquivoExame _file = new clArquivoExame("Exame.txt");
        _file.openFile();
        _file.writeInFile(nCodigoExame + "\t" + DescricaoExame + "\t" + RequisitoExame + "\r\n");
        _file.closeFile();

        jtDescricaoExame.setText("");
        jtRequisitoExame.setText("");

        }


    }//GEN-LAST:event_jbCadastrarSintomaActionPerformed

    private void jbCancelarSintomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarSintomaActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
}//GEN-LAST:event_jbCancelarSintomaActionPerformed

    private void jtDescricaoExameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtDescricaoExameActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jtDescricaoExameActionPerformed

    private void jtRequisitoExameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtRequisitoExameActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jtRequisitoExameActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfCadExame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbCadastrarSintoma;
    private javax.swing.JButton jbCancelarSintoma;
    private javax.swing.JTextField jtDescricaoExame;
    private javax.swing.JTextField jtRequisitoExame;
    // End of variables declaration//GEN-END:variables

}
