
package projeto2;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.SwingConstants;

public class jfPRINCIPAL extends javax.swing.JFrame {

    /** Creates new form jfPRINCIPAL */
    public jfPRINCIPAL() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        jSeparator1 = new javax.swing.JSeparator();
        JLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArquivo = new javax.swing.JMenu();
        jMenuArquivoSair = new javax.swing.JMenuItem();
        jMenuCadastros = new javax.swing.JMenu();
        jMenuCadPacientes = new javax.swing.JMenuItem();
        jMenuCadMedicos = new javax.swing.JMenuItem();
        jMenuCadSintomas = new javax.swing.JMenuItem();
        jMenuCadExames = new javax.swing.JMenuItem();
        jMenuCadRExames = new javax.swing.JMenuItem();
        jMenuRelatorios = new javax.swing.JMenu();
        jMenuRelLiPaci = new javax.swing.JMenuItem();
        jMenuRealLiMed = new javax.swing.JMenuItem();
        jMenuRelLiSint = new javax.swing.JMenuItem();
        jMenuRelLiExam = new javax.swing.JMenuItem();
        jMenuRelLiRexam = new javax.swing.JMenuItem();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Médico");
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        JLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto2/ambulância-do-símbolo-cuidado-thumb7959406.jpg"))); // NOI18N
        JLabel.setAlignmentY(0.0F);
        JLabel.setComponentPopupMenu(jPopupMenu1);

        jMenuArquivo.setText("Aquivo");

        jMenuArquivoSair.setText("Sair");
        jMenuArquivoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuArquivoSairActionPerformed(evt);
            }
        });
        jMenuArquivo.add(jMenuArquivoSair);

        jMenuBar1.add(jMenuArquivo);

        jMenuCadastros.setText("Cadastros");

        jMenuCadPacientes.setText("Pacientes");
        jMenuCadPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadPacientesActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuCadPacientes);

        jMenuCadMedicos.setText("Médicos");
        jMenuCadMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadMedicosActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuCadMedicos);

        jMenuCadSintomas.setText("Sintomas");
        jMenuCadSintomas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadSintomasActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuCadSintomas);

        jMenuCadExames.setText("Exames");
        jMenuCadExames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadExamesActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuCadExames);

        jMenuCadRExames.setText("Realizar Exames");
        jMenuCadRExames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadRExamesActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuCadRExames);

        jMenuBar1.add(jMenuCadastros);

        jMenuRelatorios.setText("Relatórios");

        jMenuRelLiPaci.setText("Listagem Pacientes");
        jMenuRelLiPaci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRelLiPaciActionPerformed(evt);
            }
        });
        jMenuRelatorios.add(jMenuRelLiPaci);

        jMenuRealLiMed.setText("Listagem Médicos");
        jMenuRealLiMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRealLiMedActionPerformed(evt);
            }
        });
        jMenuRelatorios.add(jMenuRealLiMed);

        jMenuRelLiSint.setText("Listagem Sintomas");
        jMenuRelLiSint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRelLiSintActionPerformed(evt);
            }
        });
        jMenuRelatorios.add(jMenuRelLiSint);

        jMenuRelLiExam.setText("Listagem Exames");
        jMenuRelLiExam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRelLiExamActionPerformed(evt);
            }
        });
        jMenuRelatorios.add(jMenuRelLiExam);

        jMenuRelLiRexam.setText("Listagem Exames Realizados");
        jMenuRelLiRexam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRelLiRexamActionPerformed(evt);
            }
        });
        jMenuRelatorios.add(jMenuRelLiRexam);

        jMenuBar1.add(jMenuRelatorios);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuCadPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadPacientesActionPerformed
        jfCadPaciente CadPaciente = new jfCadPaciente();
        CadPaciente.show();
}//GEN-LAST:event_jMenuCadPacientesActionPerformed

    private void jMenuCadSintomasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadSintomasActionPerformed
        jfCadSintomas CadSintomas = new jfCadSintomas();
        CadSintomas.show();
}//GEN-LAST:event_jMenuCadSintomasActionPerformed

    private void jMenuCadMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadMedicosActionPerformed
        jfCadMedico CadMedico = new jfCadMedico();
        CadMedico.show();
}//GEN-LAST:event_jMenuCadMedicosActionPerformed

    private void jMenuCadExamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadExamesActionPerformed
        jfCadExame CadExame = new jfCadExame();
        CadExame.show();
}//GEN-LAST:event_jMenuCadExamesActionPerformed

    private void jMenuCadRExamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadRExamesActionPerformed
        jfRealizarExames RealizarExames = new jfRealizarExames();
        RealizarExames.show();
}//GEN-LAST:event_jMenuCadRExamesActionPerformed

    private void jMenuRelLiPaciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRelLiPaciActionPerformed
        jfRelLiPaci RelLiPaci = new jfRelLiPaci();
        RelLiPaci.show();
    }//GEN-LAST:event_jMenuRelLiPaciActionPerformed

    private void jMenuRealLiMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRealLiMedActionPerformed
        jfRelLiMed RelLiMed = new jfRelLiMed();
        RelLiMed.show();
    }//GEN-LAST:event_jMenuRealLiMedActionPerformed

    private void jMenuRelLiSintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRelLiSintActionPerformed
        jfRelLiSint RelLiSint = new jfRelLiSint();
        RelLiSint.show();
    }//GEN-LAST:event_jMenuRelLiSintActionPerformed

    private void jMenuRelLiExamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRelLiExamActionPerformed
        jfRelLiExame RelLiExame = new jfRelLiExame();
        RelLiExame.show();
    }//GEN-LAST:event_jMenuRelLiExamActionPerformed

    private void jMenuRelLiRexamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRelLiRexamActionPerformed
        jfRelLiRExame RelLiRExame = new jfRelLiRExame();
        RelLiRExame.show();
    }//GEN-LAST:event_jMenuRelLiRexamActionPerformed

    private void jMenuArquivoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuArquivoSairActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jMenuArquivoSairActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
    }//GEN-LAST:event_formComponentShown


    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfPRINCIPAL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel;
    private javax.swing.JMenu jMenuArquivo;
    private javax.swing.JMenuItem jMenuArquivoSair;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCadExames;
    private javax.swing.JMenuItem jMenuCadMedicos;
    private javax.swing.JMenuItem jMenuCadPacientes;
    private javax.swing.JMenuItem jMenuCadRExames;
    private javax.swing.JMenuItem jMenuCadSintomas;
    private javax.swing.JMenu jMenuCadastros;
    private javax.swing.JMenuItem jMenuRealLiMed;
    private javax.swing.JMenuItem jMenuRelLiExam;
    private javax.swing.JMenuItem jMenuRelLiPaci;
    private javax.swing.JMenuItem jMenuRelLiRexam;
    private javax.swing.JMenuItem jMenuRelLiSint;
    private javax.swing.JMenu jMenuRelatorios;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JSeparator jSeparator1;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    // End of variables declaration//GEN-END:variables

}
