package projeto2;

import java.io.BufferedReader;
import java.io.FileReader;
import java.util.StringTokenizer;
import javax.swing.table.DefaultTableModel;

public class jfRelLiExame_1 extends javax.swing.JFrame {

    /** Creates new form jfRelLiExame */
    public jfRelLiExame_1() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtRelLiExame = new javax.swing.JTable();
        jbRelLiExameFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Relatório Listagem de Exames");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(":: Relatório Listagem de Exames ::");

        jtRelLiExame.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição", "Requisitos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtRelLiExame);
        jtRelLiExame.getColumnModel().getColumn(0).setResizable(false);
        jtRelLiExame.getColumnModel().getColumn(1).setResizable(false);
        jtRelLiExame.getColumnModel().getColumn(2).setResizable(false);

        jbRelLiExameFechar.setText("Fechar");
        jbRelLiExameFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRelLiExameFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jLabel2)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addComponent(jbRelLiExameFechar)
                .addContainerGap(242, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jbRelLiExameFechar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
       //Vetores pacientes
       String [] aCodExame = new String[100];
       final String [] aNomeExame = new String[100];
       final String [] aRequisitosExame = new String[100];

       int nExame = 0;

       String linhaExame;
       try {
          FileReader reader = new FileReader("Exame.txt");
          BufferedReader leitor = new BufferedReader(reader);
          StringTokenizer st = null;

          while ((linhaExame = leitor.readLine()) != null) {

             st = new StringTokenizer(linhaExame, "\t");
             String dados = null;

             while (st.hasMoreTokens()) {

                // Código
                dados = st.nextToken();
                System.out.println(dados);
                aCodExame[nExame] = dados;

                // Descrição
                dados = st.nextToken();
                System.out.println(dados);
                aNomeExame[nExame] = dados;

                // Requisitos
                dados = st.nextToken();
                System.out.println(dados);
                aRequisitosExame[nExame] = dados;

                nExame ++;

             }
          }

          leitor.close();
          reader.close();

       } catch (Exception e) {
          e.printStackTrace();
       }


        DefaultTableModel model = (DefaultTableModel) jtRelLiExame.getModel();
        for(int i = 0; i < aCodExame.length; i++ )
        {
            Object[] o = new Object[]{ aCodExame[i],  aNomeExame[i],  aRequisitosExame[i] };
            model.addRow(o);
        }


    }//GEN-LAST:event_formComponentShown

    private void jbRelLiExameFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRelLiExameFecharActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
}//GEN-LAST:event_jbRelLiExameFecharActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfRelLiExame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbRelLiExameFechar;
    private javax.swing.JTable jtRelLiExame;
    // End of variables declaration//GEN-END:variables

}
