package projeto2;

import java.io.BufferedReader;
import java.io.FileReader;
import java.util.StringTokenizer;
import javax.swing.table.DefaultTableModel;

public class jfRelLiRExame extends javax.swing.JFrame {

   //Vetores pacientes
   String [] aCodRExame = new String[100];
   final String [] aMedicoRExame = new String[100];
   final String [] aPacienteRExame = new String[100];
   final String [] aSintomaRExame = new String[100];
   final String [] aExameRExame = new String[100];
   final String [] aDiagnosticoRExame = new String[100];



    /** Creates new form jfRelLiRExame */
    public jfRelLiRExame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jtRelLiRExame = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jbRelLiRExameFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Relatório Listagem de Exames Realizados");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(":: Relatório Listagem de Exames Realizados ::");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Médico", "Paciente", "Sintoma", "Exame", "Diagnóstico"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtRelLiRExame.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setResizable(false);
        jTable1.getColumnModel().getColumn(1).setResizable(false);
        jTable1.getColumnModel().getColumn(2).setResizable(false);
        jTable1.getColumnModel().getColumn(3).setResizable(false);
        jTable1.getColumnModel().getColumn(4).setResizable(false);
        jTable1.getColumnModel().getColumn(5).setResizable(false);

        jbRelLiRExameFechar.setText("Fechar");
        jbRelLiRExameFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRelLiRExameFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtRelLiRExame, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jLabel2))
            .addGroup(layout.createSequentialGroup()
                .addGap(336, 336, 336)
                .addComponent(jbRelLiRExameFechar))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jtRelLiRExame, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbRelLiRExameFechar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbRelLiRExameFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRelLiRExameFecharActionPerformed
        this.setVisible(false);
}//GEN-LAST:event_jbRelLiRExameFecharActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown

       int nRExame = 0;

       String linhaMed;
       try {
          FileReader reader = new FileReader("RExame.txt");
          BufferedReader leitor = new BufferedReader(reader);
          StringTokenizer st = null;

          while ((linhaMed = leitor.readLine()) != null) {

             st = new StringTokenizer(linhaMed, "\t");
             String dados = null;

             while (st.hasMoreTokens()) {

                // Código
                dados = st.nextToken();
                System.out.println(dados);
                aCodRExame[nRExame] = dados;

                // Médico
                dados = st.nextToken();
                System.out.println(dados);
                aMedicoRExame[nRExame] = dados;

                // Paciente
                dados = st.nextToken();
                System.out.println(dados);
                aPacienteRExame[nRExame] = dados;

                // Sintoma
                dados = st.nextToken();
                System.out.println(dados);
                aSintomaRExame[nRExame] = dados;

                // Exame
                dados = st.nextToken();
                System.out.println(dados);
                aExameRExame[nRExame] = dados;

                // Diagnóstico
                dados = st.nextToken();
                System.out.println(dados);
                aDiagnosticoRExame[nRExame] = dados;

                nRExame ++;

             }
          }

          leitor.close();
          reader.close();

       } catch (Exception e) {
          e.printStackTrace();
       }


        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        for(int i = 0; i < aCodRExame.length; i++ )
        {
            Object[] o = new Object[]{ aCodRExame[i],  aMedicoRExame[i],  aPacienteRExame[i],  aSintomaRExame[i],  aExameRExame[i],  aDiagnosticoRExame[i] };
            model.addRow(o);
        }


    }//GEN-LAST:event_formComponentShown

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized

    }//GEN-LAST:event_formComponentResized

    
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfRelLiRExame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbRelLiRExameFechar;
    private javax.swing.JScrollPane jtRelLiRExame;
    // End of variables declaration//GEN-END:variables

}
