/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Nim.java
 *
 * Created on Sep 8, 2010, 6:01:46 PM
 */
package socketsjava;

import java.io.IOException;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author leandro
 */
public class Nim extends javax.swing.JFrame {

    int nLinha = 0;
    int nQtd = 0;

    /** Creates new form Nim */
    public Nim() {
        initComponents();
        jTextField2.setText("192.168.238.128");
        jTextField1.setText("55555");
    }

    public void Marcar(boolean lMarc) {
        lbPalito_01.setVisible(lMarc);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jbConectar = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jbEnviar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbPalito_01 = new javax.swing.JLabel();
        jbPalito_11 = new javax.swing.JToggleButton();
        jbPalito_12 = new javax.swing.JToggleButton();
        jbPalito_13 = new javax.swing.JToggleButton();
        jbPalito_14 = new javax.swing.JToggleButton();
        jbPalito_15 = new javax.swing.JToggleButton();
        jbPalito_16 = new javax.swing.JToggleButton();
        jbPalito_17 = new javax.swing.JToggleButton();
        jbPalito_18 = new javax.swing.JToggleButton();
        jbPalito_19 = new javax.swing.JToggleButton();
        jbPalito_21 = new javax.swing.JToggleButton();
        jbPalito_22 = new javax.swing.JToggleButton();
        jbPalito_23 = new javax.swing.JToggleButton();
        jbPalito_24 = new javax.swing.JToggleButton();
        jbPalito_25 = new javax.swing.JToggleButton();
        jbPalito_26 = new javax.swing.JToggleButton();
        jbPalito_27 = new javax.swing.JToggleButton();
        jbPalito_28 = new javax.swing.JToggleButton();
        jbPalito_29 = new javax.swing.JToggleButton();
        jbPalito_31 = new javax.swing.JToggleButton();
        jbPalito_32 = new javax.swing.JToggleButton();
        jbPalito_33 = new javax.swing.JToggleButton();
        jbPalito_34 = new javax.swing.JToggleButton();
        jbPalito_35 = new javax.swing.JToggleButton();
        jbPalito_36 = new javax.swing.JToggleButton();
        jbPalito_37 = new javax.swing.JToggleButton();
        jbPalito_38 = new javax.swing.JToggleButton();
        jbPalito_39 = new javax.swing.JToggleButton();
        jbPalito_41 = new javax.swing.JToggleButton();
        jbPalito_42 = new javax.swing.JToggleButton();
        jbPalito_43 = new javax.swing.JToggleButton();
        jbPalito_44 = new javax.swing.JToggleButton();
        jbPalito_45 = new javax.swing.JToggleButton();
        jbPalito_46 = new javax.swing.JToggleButton();
        jbPalito_47 = new javax.swing.JToggleButton();
        jbPalito_48 = new javax.swing.JToggleButton();
        jbPalito_49 = new javax.swing.JToggleButton();
        jbPalito_51 = new javax.swing.JToggleButton();
        jbPalito_52 = new javax.swing.JToggleButton();
        jbPalito_53 = new javax.swing.JToggleButton();
        jbPalito_54 = new javax.swing.JToggleButton();
        jbPalito_55 = new javax.swing.JToggleButton();
        jbPalito_56 = new javax.swing.JToggleButton();
        jbPalito_57 = new javax.swing.JToggleButton();
        jbPalito_58 = new javax.swing.JToggleButton();
        jbPalito_59 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbConectar.setText("Conectar");
        jbConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConectarActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jbEnviar.setText("Enviar");
        jbEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEnviarActionPerformed(evt);
            }
        });

        jLabel2.setText("IP:");

        jLabel3.setText("Porta:");

        lbPalito_01.setBackground(new java.awt.Color(176, 42, 42));
        lbPalito_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito.jpg"))); // NOI18N
        lbPalito_01.setLabelFor(jPanel1);
        lbPalito_01.setText("123");

        jbPalito_11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito.jpg"))); // NOI18N
        jbPalito_11.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito2.jpg"))); // NOI18N
        jbPalito_11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPalito_11ActionPerformed(evt);
            }
        });

        jbPalito_12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito.jpg"))); // NOI18N
        jbPalito_12.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito2.jpg"))); // NOI18N
        jbPalito_12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPalito_12ActionPerformed(evt);
            }
        });

        jbPalito_13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito.jpg"))); // NOI18N
        jbPalito_13.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito2.jpg"))); // NOI18N
        jbPalito_13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPalito_13ActionPerformed(evt);
            }
        });

        jbPalito_14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito.jpg"))); // NOI18N
        jbPalito_14.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito2.jpg"))); // NOI18N
        jbPalito_14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPalito_14ActionPerformed(evt);
            }
        });

        jbPalito_15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito.jpg"))); // NOI18N
        jbPalito_15.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito2.jpg"))); // NOI18N
        jbPalito_15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPalito_15ActionPerformed(evt);
            }
        });

        jbPalito_16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito.jpg"))); // NOI18N
        jbPalito_16.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito2.jpg"))); // NOI18N
        jbPalito_16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPalito_16ActionPerformed(evt);
            }
        });

        jbPalito_17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito.jpg"))); // NOI18N
        jbPalito_17.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito2.jpg"))); // NOI18N
        jbPalito_17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPalito_17ActionPerformed(evt);
            }
        });

        jbPalito_18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito.jpg"))); // NOI18N
        jbPalito_18.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito2.jpg"))); // NOI18N
        jbPalito_18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPalito_18ActionPerformed(evt);
            }
        });

        jbPalito_19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito.jpg"))); // NOI18N
        jbPalito_19.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito2.jpg"))); // NOI18N
        jbPalito_19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPalito_19ActionPerformed(evt);
            }
        });

        jbPalito_21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito.jpg"))); // NOI18N
        jbPalito_21.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito2.jpg"))); // NOI18N
        jbPalito_21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPalito_21ActionPerformed(evt);
            }
        });

        jbPalito_22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito.jpg"))); // NOI18N
        jbPalito_22.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito2.jpg"))); // NOI18N
        jbPalito_22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPalito_22ActionPerformed(evt);
            }
        });

        jbPalito_23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito.jpg"))); // NOI18N
        jbPalito_23.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito2.jpg"))); // NOI18N
        jbPalito_23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPalito_23ActionPerformed(evt);
            }
        });

        jbPalito_24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito.jpg"))); // NOI18N
        jbPalito_24.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito2.jpg"))); // NOI18N
        jbPalito_24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPalito_24ActionPerformed(evt);
            }
        });

        jbPalito_25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito.jpg"))); // NOI18N
        jbPalito_25.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito2.jpg"))); // NOI18N
        jbPalito_25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPalito_25ActionPerformed(evt);
            }
        });

        jbPalito_26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito.jpg"))); // NOI18N
        jbPalito_26.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito2.jpg"))); // NOI18N
        jbPalito_26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPalito_26ActionPerformed(evt);
            }
        });

        jbPalito_27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito.jpg"))); // NOI18N
        jbPalito_27.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito2.jpg"))); // NOI18N
        jbPalito_27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPalito_27ActionPerformed(evt);
            }
        });

        jbPalito_28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito.jpg"))); // NOI18N
        jbPalito_28.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito2.jpg"))); // NOI18N
        jbPalito_28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPalito_28ActionPerformed(evt);
            }
        });

        jbPalito_29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito.jpg"))); // NOI18N
        jbPalito_29.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito2.jpg"))); // NOI18N
        jbPalito_29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPalito_29ActionPerformed(evt);
            }
        });

        jbPalito_31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito.jpg"))); // NOI18N
        jbPalito_31.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito2.jpg"))); // NOI18N
        jbPalito_31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPalito_31ActionPerformed(evt);
            }
        });

        jbPalito_32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito.jpg"))); // NOI18N
        jbPalito_32.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito2.jpg"))); // NOI18N
        jbPalito_32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPalito_32ActionPerformed(evt);
            }
        });

        jbPalito_33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito.jpg"))); // NOI18N
        jbPalito_33.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito2.jpg"))); // NOI18N
        jbPalito_33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPalito_33ActionPerformed(evt);
            }
        });

        jbPalito_34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito.jpg"))); // NOI18N
        jbPalito_34.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito2.jpg"))); // NOI18N
        jbPalito_34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPalito_34ActionPerformed(evt);
            }
        });

        jbPalito_35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito.jpg"))); // NOI18N
        jbPalito_35.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito2.jpg"))); // NOI18N
        jbPalito_35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPalito_35ActionPerformed(evt);
            }
        });

        jbPalito_36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito.jpg"))); // NOI18N
        jbPalito_36.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito2.jpg"))); // NOI18N
        jbPalito_36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPalito_36ActionPerformed(evt);
            }
        });

        jbPalito_37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito.jpg"))); // NOI18N
        jbPalito_37.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito2.jpg"))); // NOI18N
        jbPalito_37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPalito_37ActionPerformed(evt);
            }
        });

        jbPalito_38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito.jpg"))); // NOI18N
        jbPalito_38.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito2.jpg"))); // NOI18N
        jbPalito_38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPalito_38ActionPerformed(evt);
            }
        });

        jbPalito_39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito.jpg"))); // NOI18N
        jbPalito_39.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito2.jpg"))); // NOI18N
        jbPalito_39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPalito_39ActionPerformed(evt);
            }
        });

        jbPalito_41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito.jpg"))); // NOI18N
        jbPalito_41.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito2.jpg"))); // NOI18N
        jbPalito_41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPalito_41ActionPerformed(evt);
            }
        });

        jbPalito_42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito.jpg"))); // NOI18N
        jbPalito_42.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito2.jpg"))); // NOI18N
        jbPalito_42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPalito_42ActionPerformed(evt);
            }
        });

        jbPalito_43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito.jpg"))); // NOI18N
        jbPalito_43.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito2.jpg"))); // NOI18N
        jbPalito_43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPalito_43ActionPerformed(evt);
            }
        });

        jbPalito_44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito.jpg"))); // NOI18N
        jbPalito_44.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito2.jpg"))); // NOI18N
        jbPalito_44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPalito_44ActionPerformed(evt);
            }
        });

        jbPalito_45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito.jpg"))); // NOI18N
        jbPalito_45.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito2.jpg"))); // NOI18N
        jbPalito_45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPalito_45ActionPerformed(evt);
            }
        });

        jbPalito_46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito.jpg"))); // NOI18N
        jbPalito_46.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito2.jpg"))); // NOI18N
        jbPalito_46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPalito_46ActionPerformed(evt);
            }
        });

        jbPalito_47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito.jpg"))); // NOI18N
        jbPalito_47.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito2.jpg"))); // NOI18N
        jbPalito_47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPalito_47ActionPerformed(evt);
            }
        });

        jbPalito_48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito.jpg"))); // NOI18N
        jbPalito_48.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito2.jpg"))); // NOI18N
        jbPalito_48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPalito_48ActionPerformed(evt);
            }
        });

        jbPalito_49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito.jpg"))); // NOI18N
        jbPalito_49.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito2.jpg"))); // NOI18N
        jbPalito_49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPalito_49ActionPerformed(evt);
            }
        });

        jbPalito_51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito.jpg"))); // NOI18N
        jbPalito_51.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito2.jpg"))); // NOI18N
        jbPalito_51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPalito_51ActionPerformed(evt);
            }
        });

        jbPalito_52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito.jpg"))); // NOI18N
        jbPalito_52.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito2.jpg"))); // NOI18N
        jbPalito_52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPalito_52ActionPerformed(evt);
            }
        });

        jbPalito_53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito.jpg"))); // NOI18N
        jbPalito_53.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito2.jpg"))); // NOI18N
        jbPalito_53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPalito_53ActionPerformed(evt);
            }
        });

        jbPalito_54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito.jpg"))); // NOI18N
        jbPalito_54.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito2.jpg"))); // NOI18N
        jbPalito_54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPalito_54ActionPerformed(evt);
            }
        });

        jbPalito_55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito.jpg"))); // NOI18N
        jbPalito_55.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito2.jpg"))); // NOI18N
        jbPalito_55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPalito_55ActionPerformed(evt);
            }
        });

        jbPalito_56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito.jpg"))); // NOI18N
        jbPalito_56.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito2.jpg"))); // NOI18N
        jbPalito_56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPalito_56ActionPerformed(evt);
            }
        });

        jbPalito_57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito.jpg"))); // NOI18N
        jbPalito_57.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito2.jpg"))); // NOI18N
        jbPalito_57.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPalito_57ActionPerformed(evt);
            }
        });

        jbPalito_58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito.jpg"))); // NOI18N
        jbPalito_58.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito2.jpg"))); // NOI18N
        jbPalito_58.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPalito_58ActionPerformed(evt);
            }
        });

        jbPalito_59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito.jpg"))); // NOI18N
        jbPalito_59.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/socketsjava/Palito2.jpg"))); // NOI18N
        jbPalito_59.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPalito_59ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbPalito_21, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbPalito_22, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbPalito_23, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbPalito_24, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbPalito_25, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbPalito_26, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbPalito_27, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbPalito_28, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbPalito_29, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbPalito_11, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbPalito_12, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbPalito_13, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbPalito_14, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbPalito_15, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbPalito_16, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbPalito_17, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbPalito_18, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbPalito_19, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbPalito_31, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbPalito_41, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jbPalito_42, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbPalito_43, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbPalito_44, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbPalito_45, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbPalito_46, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbPalito_47, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbPalito_48, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbPalito_49, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jbPalito_32, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbPalito_33, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbPalito_34, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbPalito_35, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbPalito_36, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbPalito_37, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbPalito_38, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbPalito_39, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbPalito_51, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbPalito_52, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbPalito_53, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbPalito_54, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbPalito_55, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbPalito_56, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbPalito_57, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbPalito_58, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbPalito_59, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(lbPalito_01, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbEnviar))
                        .addGap(765, 765, 765))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(623, 623, 623)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jbConectar)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbPalito_12, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbPalito_11, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbPalito_13, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbPalito_14, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbPalito_15, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbPalito_16, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbPalito_17, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbPalito_18, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbPalito_19, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbConectar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbPalito_22, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbPalito_21, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbPalito_23, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbPalito_24, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbPalito_25, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbPalito_26, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbPalito_27, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbPalito_28, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbPalito_29, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(lbPalito_01)
                        .addGap(66, 66, 66)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbEnviar)
                        .addGap(79, 79, 79))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbPalito_31, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbPalito_32, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbPalito_33, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbPalito_34, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbPalito_35, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbPalito_36, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbPalito_37, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbPalito_38, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbPalito_39, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbPalito_49, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbPalito_48, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbPalito_47, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbPalito_46, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbPalito_45, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbPalito_44, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbPalito_43, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbPalito_42, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbPalito_41, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbPalito_54, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbPalito_59, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbPalito_58, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbPalito_57, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbPalito_56, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbPalito_55, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbPalito_53, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbPalito_52, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbPalito_51, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 976, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConectarActionPerformed

        try {
            tcpclient = new TCPClient(jTextField2.getText(), Integer.parseInt(jTextField1.getText()));
            new ClienteThread(this).start();


            if (tcpclient != null) {
                tcpclient.writeMessage("PPP");
            }


        } catch (UnknownHostException ex) {
            Logger.getLogger(Nim.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Nim.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jbConectarActionPerformed

    private void jbEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEnviarActionPerformed
        // TODO add your handling code here:
        if (tcpclient != null) {
            tcpclient.writeMessage(jTextField3.getText());
        }

    }//GEN-LAST:event_jbEnviarActionPerformed

    private void jbPalito_11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPalito_11ActionPerformed

        if ((nQtd > 0) && (nLinha != 1)) {

            JOptionPane.showMessageDialog(null, "Apenas uma fileira de palitos pode ser mexida!");
            jbPalito_11.setSelected(false);

        } else {
            if (jbPalito_11.isSelected()) {
                nLinha = 1;
                nQtd++;
            } else {
                nQtd--;
                if (nQtd == 0) {
                    nLinha = 0;
                }
            }

        }

        System.out.println("Linha: " + nLinha + " " + "QTD: " + nQtd);

    }//GEN-LAST:event_jbPalito_11ActionPerformed

    private void jbPalito_12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPalito_12ActionPerformed

        if ((nQtd > 0) && (nLinha != 1)) {

            JOptionPane.showMessageDialog(null, "Apenas uma fileira de palitos pode ser mexida!");
            jbPalito_12.setSelected(false);

        } else {
            if (jbPalito_12.isSelected()) {
                nLinha = 1;
                nQtd++;
            } else {
                nQtd--;
                if (nQtd == 0) {
                    nLinha = 0;
                }
            }

        }

        System.out.println("Linha: " + nLinha + " " + "QTD: " + nQtd);

    }//GEN-LAST:event_jbPalito_12ActionPerformed

    private void jbPalito_13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPalito_13ActionPerformed

        if ((nQtd > 0) && (nLinha != 1)) {

            JOptionPane.showMessageDialog(null, "Apenas uma fileira de palitos pode ser mexida!");
            jbPalito_13.setSelected(false);

        } else {
            if (jbPalito_13.isSelected()) {
                nLinha = 1;
                nQtd++;
            } else {
                nQtd--;
                if (nQtd == 0) {
                    nLinha = 0;
                }
            }

        }

        System.out.println("Linha: " + nLinha + " " + "QTD: " + nQtd);

    }//GEN-LAST:event_jbPalito_13ActionPerformed

    private void jbPalito_14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPalito_14ActionPerformed

        if ((nQtd > 0) && (nLinha != 1)) {

            JOptionPane.showMessageDialog(null, "Apenas uma fileira de palitos pode ser mexida!");
            jbPalito_14.setSelected(false);

        } else {
            if (jbPalito_14.isSelected()) {
                nLinha = 1;
                nQtd++;
            } else {
                nQtd--;
                if (nQtd == 0) {
                    nLinha = 0;
                }
            }

        }

        System.out.println("Linha: " + nLinha + " " + "QTD: " + nQtd);

    }//GEN-LAST:event_jbPalito_14ActionPerformed

    private void jbPalito_15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPalito_15ActionPerformed

        if ((nQtd > 0) && (nLinha != 1)) {

            JOptionPane.showMessageDialog(null, "Apenas uma fileira de palitos pode ser mexida!");
            jbPalito_15.setSelected(false);

        } else {
            if (jbPalito_15.isSelected()) {
                nLinha = 1;
                nQtd++;
            } else {
                nQtd--;
                if (nQtd == 0) {
                    nLinha = 0;
                }
            }

        }

        System.out.println("Linha: " + nLinha + " " + "QTD: " + nQtd);

    }//GEN-LAST:event_jbPalito_15ActionPerformed

    private void jbPalito_16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPalito_16ActionPerformed

        if ((nQtd > 0) && (nLinha != 1)) {

            JOptionPane.showMessageDialog(null, "Apenas uma fileira de palitos pode ser mexida!");
            jbPalito_16.setSelected(false);

        } else {
            if (jbPalito_16.isSelected()) {
                nLinha = 1;
                nQtd++;
            } else {
                nQtd--;
                if (nQtd == 0) {
                    nLinha = 0;
                }
            }

        }

        System.out.println("Linha: " + nLinha + " " + "QTD: " + nQtd);

    }//GEN-LAST:event_jbPalito_16ActionPerformed

    private void jbPalito_17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPalito_17ActionPerformed

        if ((nQtd > 0) && (nLinha != 1)) {
            JOptionPane.showMessageDialog(null, "Apenas uma fileira de palitos pode ser mexida!");
            jbPalito_17.setSelected(false);
        } else {
            if (jbPalito_17.isSelected()) {
                nLinha = 1;
                nQtd++;
            } else {
                nQtd--;
                if (nQtd == 0) {
                    nLinha = 0;
                }
            }
        }
        System.out.println("Linha: " + nLinha + " " + "QTD: " + nQtd);

    }//GEN-LAST:event_jbPalito_17ActionPerformed

    private void jbPalito_18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPalito_18ActionPerformed

        if ((nQtd > 0) && (nLinha != 1)) {

            JOptionPane.showMessageDialog(null, "Apenas uma fileira de palitos pode ser mexida!");
            jbPalito_18.setSelected(false);

        } else {
            if (jbPalito_18.isSelected()) {
                nLinha = 1;
                nQtd++;
            } else {
                nQtd--;
                if (nQtd == 0) {
                    nLinha = 0;
                }
            }

        }

        System.out.println("Linha: " + nLinha + " " + "QTD: " + nQtd);

    }//GEN-LAST:event_jbPalito_18ActionPerformed

    private void jbPalito_19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPalito_19ActionPerformed

        if ((nQtd > 0) && (nLinha != 1)) {

            JOptionPane.showMessageDialog(null, "Apenas uma fileira de palitos pode ser mexida!");
            jbPalito_19.setSelected(false);

        } else {
            if (jbPalito_19.isSelected()) {
                nLinha = 1;
                nQtd++;
            } else {
                nQtd--;
                if (nQtd == 0) {
                    nLinha = 0;
                }
            }

        }

        System.out.println("Linha: " + nLinha + " " + "QTD: " + nQtd);

    }//GEN-LAST:event_jbPalito_19ActionPerformed

    private void jbPalito_21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPalito_21ActionPerformed

        if ((nQtd > 0) && (nLinha != 2)) {

            JOptionPane.showMessageDialog(null, "Apenas uma fileira de palitos pode ser mexida!");
            jbPalito_21.setSelected(false);

        } else {
            if (jbPalito_21.isSelected()) {
                nLinha = 2;
                nQtd++;
            } else {
                nQtd--;
                if (nQtd == 0) {
                    nLinha = 0;
                }
            }

        }

        System.out.println("Linha: " + nLinha + " " + "QTD: " + nQtd);

    }//GEN-LAST:event_jbPalito_21ActionPerformed

    private void jbPalito_22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPalito_22ActionPerformed

        if ((nQtd > 0) && (nLinha != 2)) {

            JOptionPane.showMessageDialog(null, "Apenas uma fileira de palitos pode ser mexida!");
            jbPalito_22.setSelected(false);

        } else {
            if (jbPalito_22.isSelected()) {
                nLinha = 2;
                nQtd++;
            } else {
                nQtd--;
                if (nQtd == 0) {
                    nLinha = 0;
                }
            }

        }

        System.out.println("Linha: " + nLinha + " " + "QTD: " + nQtd);

    }//GEN-LAST:event_jbPalito_22ActionPerformed

    private void jbPalito_23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPalito_23ActionPerformed

        if ((nQtd > 0) && (nLinha != 2)) {

            JOptionPane.showMessageDialog(null, "Apenas uma fileira de palitos pode ser mexida!");
            jbPalito_23.setSelected(false);

        } else {
            if (jbPalito_23.isSelected()) {
                nLinha = 2;
                nQtd++;
            } else {
                nQtd--;
                if (nQtd == 0) {
                    nLinha = 0;
                }
            }

        }

        System.out.println("Linha: " + nLinha + " " + "QTD: " + nQtd);

    }//GEN-LAST:event_jbPalito_23ActionPerformed

    private void jbPalito_24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPalito_24ActionPerformed

        if ((nQtd > 0) && (nLinha != 2)) {

            JOptionPane.showMessageDialog(null, "Apenas uma fileira de palitos pode ser mexida!");
            jbPalito_24.setSelected(false);

        } else {
            if (jbPalito_24.isSelected()) {
                nLinha = 2;
                nQtd++;
            } else {
                nQtd--;
                if (nQtd == 0) {
                    nLinha = 0;
                }
            }

        }

        System.out.println("Linha: " + nLinha + " " + "QTD: " + nQtd);

    }//GEN-LAST:event_jbPalito_24ActionPerformed

    private void jbPalito_25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPalito_25ActionPerformed

        if ((nQtd > 0) && (nLinha != 2)) {

            JOptionPane.showMessageDialog(null, "Apenas uma fileira de palitos pode ser mexida!");
            jbPalito_25.setSelected(false);

        } else {
            if (jbPalito_25.isSelected()) {
                nLinha = 2;
                nQtd++;
            } else {
                nQtd--;
                if (nQtd == 0) {
                    nLinha = 0;
                }
            }

        }

        System.out.println("Linha: " + nLinha + " " + "QTD: " + nQtd);

    }//GEN-LAST:event_jbPalito_25ActionPerformed

    private void jbPalito_26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPalito_26ActionPerformed

        if ((nQtd > 0) && (nLinha != 2)) {

            JOptionPane.showMessageDialog(null, "Apenas uma fileira de palitos pode ser mexida!");
            jbPalito_26.setSelected(false);

        } else {
            if (jbPalito_26.isSelected()) {
                nLinha = 2;
                nQtd++;
            } else {
                nQtd--;
                if (nQtd == 0) {
                    nLinha = 0;
                }
            }

        }

        System.out.println("Linha: " + nLinha + " " + "QTD: " + nQtd);

    }//GEN-LAST:event_jbPalito_26ActionPerformed

    private void jbPalito_27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPalito_27ActionPerformed

        if ((nQtd > 0) && (nLinha != 2)) {

            JOptionPane.showMessageDialog(null, "Apenas uma fileira de palitos pode ser mexida!");
            jbPalito_27.setSelected(false);

        } else {
            if (jbPalito_27.isSelected()) {
                nLinha = 2;
                nQtd++;
            } else {
                nQtd--;
                if (nQtd == 0) {
                    nLinha = 0;
                }
            }

        }

        System.out.println("Linha: " + nLinha + " " + "QTD: " + nQtd);

    }//GEN-LAST:event_jbPalito_27ActionPerformed

    private void jbPalito_28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPalito_28ActionPerformed

        if ((nQtd > 0) && (nLinha != 2)) {

            JOptionPane.showMessageDialog(null, "Apenas uma fileira de palitos pode ser mexida!");
            jbPalito_28.setSelected(false);

        } else {
            if (jbPalito_28.isSelected()) {
                nLinha = 2;
                nQtd++;
            } else {
                nQtd--;
                if (nQtd == 0) {
                    nLinha = 0;
                }
            }

        }

        System.out.println("Linha: " + nLinha + " " + "QTD: " + nQtd);

    }//GEN-LAST:event_jbPalito_28ActionPerformed

    private void jbPalito_29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPalito_29ActionPerformed

        if ((nQtd > 0) && (nLinha != 2)) {

            JOptionPane.showMessageDialog(null, "Apenas uma fileira de palitos pode ser mexida!");
            jbPalito_29.setSelected(false);

        } else {
            if (jbPalito_29.isSelected()) {
                nLinha = 2;
                nQtd++;
            } else {
                nQtd--;
                if (nQtd == 0) {
                    nLinha = 0;
                }
            }

        }

        System.out.println("Linha: " + nLinha + " " + "QTD: " + nQtd);

    }//GEN-LAST:event_jbPalito_29ActionPerformed

    private void jbPalito_31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPalito_31ActionPerformed

        if ((nQtd > 0) && (nLinha != 3)) {

            JOptionPane.showMessageDialog(null, "Apenas uma fileira de palitos pode ser mexida!");
            jbPalito_31.setSelected(false);

        } else {
            if (jbPalito_31.isSelected()) {
                nLinha = 3;
                nQtd++;
            } else {
                nQtd--;
                if (nQtd == 0) {
                    nLinha = 0;
                }
            }

        }

        System.out.println("Linha: " + nLinha + " " + "QTD: " + nQtd);

    }//GEN-LAST:event_jbPalito_31ActionPerformed

    private void jbPalito_32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPalito_32ActionPerformed

        if ((nQtd > 0) && (nLinha != 3)) {

            JOptionPane.showMessageDialog(null, "Apenas uma fileira de palitos pode ser mexida!");
            jbPalito_32.setSelected(false);

        } else {
            if (jbPalito_32.isSelected()) {
                nLinha = 3;
                nQtd++;
            } else {
                nQtd--;
                if (nQtd == 0) {
                    nLinha = 0;
                }
            }

        }

        System.out.println("Linha: " + nLinha + " " + "QTD: " + nQtd);

    }//GEN-LAST:event_jbPalito_32ActionPerformed

    private void jbPalito_33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPalito_33ActionPerformed

        if ((nQtd > 0) && (nLinha != 3)) {

            JOptionPane.showMessageDialog(null, "Apenas uma fileira de palitos pode ser mexida!");
            jbPalito_33.setSelected(false);

        } else {
            if (jbPalito_33.isSelected()) {
                nLinha = 3;
                nQtd++;
            } else {
                nQtd--;
                if (nQtd == 0) {
                    nLinha = 0;
                }
            }

        }

        System.out.println("Linha: " + nLinha + " " + "QTD: " + nQtd);

    }//GEN-LAST:event_jbPalito_33ActionPerformed

    private void jbPalito_34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPalito_34ActionPerformed

        if ((nQtd > 0) && (nLinha != 3)) {

            JOptionPane.showMessageDialog(null, "Apenas uma fileira de palitos pode ser mexida!");
            jbPalito_34.setSelected(false);

        } else {
            if (jbPalito_34.isSelected()) {
                nLinha = 3;
                nQtd++;
            } else {
                nQtd--;
                if (nQtd == 0) {
                    nLinha = 0;
                }
            }

        }

        System.out.println("Linha: " + nLinha + " " + "QTD: " + nQtd);

    }//GEN-LAST:event_jbPalito_34ActionPerformed

    private void jbPalito_35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPalito_35ActionPerformed

        if ((nQtd > 0) && (nLinha != 3)) {

            JOptionPane.showMessageDialog(null, "Apenas uma fileira de palitos pode ser mexida!");
            jbPalito_35.setSelected(false);

        } else {
            if (jbPalito_35.isSelected()) {
                nLinha = 3;
                nQtd++;
            } else {
                nQtd--;
                if (nQtd == 0) {
                    nLinha = 0;
                }
            }

        }

        System.out.println("Linha: " + nLinha + " " + "QTD: " + nQtd);

    }//GEN-LAST:event_jbPalito_35ActionPerformed

    private void jbPalito_36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPalito_36ActionPerformed

        if ((nQtd > 0) && (nLinha != 3)) {

            JOptionPane.showMessageDialog(null, "Apenas uma fileira de palitos pode ser mexida!");
            jbPalito_36.setSelected(false);

        } else {
            if (jbPalito_36.isSelected()) {
                nLinha = 3;
                nQtd++;
            } else {
                nQtd--;
                if (nQtd == 0) {
                    nLinha = 0;
                }
            }

        }

        System.out.println("Linha: " + nLinha + " " + "QTD: " + nQtd);

    }//GEN-LAST:event_jbPalito_36ActionPerformed

    private void jbPalito_37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPalito_37ActionPerformed

        if ((nQtd > 0) && (nLinha != 3)) {

            JOptionPane.showMessageDialog(null, "Apenas uma fileira de palitos pode ser mexida!");
            jbPalito_37.setSelected(false);

        } else {
            if (jbPalito_37.isSelected()) {
                nLinha = 3;
                nQtd++;
            } else {
                nQtd--;
                if (nQtd == 0) {
                    nLinha = 0;
                }
            }

        }

        System.out.println("Linha: " + nLinha + " " + "QTD: " + nQtd);

    }//GEN-LAST:event_jbPalito_37ActionPerformed

    private void jbPalito_38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPalito_38ActionPerformed

        if ((nQtd > 0) && (nLinha != 3)) {

            JOptionPane.showMessageDialog(null, "Apenas uma fileira de palitos pode ser mexida!");
            jbPalito_38.setSelected(false);

        } else {
            if (jbPalito_38.isSelected()) {
                nLinha = 3;
                nQtd++;
            } else {
                nQtd--;
                if (nQtd == 0) {
                    nLinha = 0;
                }
            }

        }

        System.out.println("Linha: " + nLinha + " " + "QTD: " + nQtd);

    }//GEN-LAST:event_jbPalito_38ActionPerformed

    private void jbPalito_39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPalito_39ActionPerformed

        if ((nQtd > 0) && (nLinha != 3)) {

            JOptionPane.showMessageDialog(null, "Apenas uma fileira de palitos pode ser mexida!");
            jbPalito_39.setSelected(false);

        } else {
            if (jbPalito_39.isSelected()) {
                nLinha = 3;
                nQtd++;
            } else {
                nQtd--;
                if (nQtd == 0) {
                    nLinha = 0;
                }
            }

        }

        System.out.println("Linha: " + nLinha + " " + "QTD: " + nQtd);

    }//GEN-LAST:event_jbPalito_39ActionPerformed

    private void jbPalito_41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPalito_41ActionPerformed

        if ((nQtd > 0) && (nLinha != 4)) {

            JOptionPane.showMessageDialog(null, "Apenas uma fileira de palitos pode ser mexida!");
            jbPalito_41.setSelected(false);

        } else {
            if (jbPalito_41.isSelected()) {
                nLinha = 4;
                nQtd++;
            } else {
                nQtd--;
                if (nQtd == 0) {
                    nLinha = 0;
                }
            }

        }

        System.out.println("Linha: " + nLinha + " " + "QTD: " + nQtd);

    }//GEN-LAST:event_jbPalito_41ActionPerformed

    private void jbPalito_42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPalito_42ActionPerformed

        if ((nQtd > 0) && (nLinha != 4)) {

            JOptionPane.showMessageDialog(null, "Apenas uma fileira de palitos pode ser mexida!");
            jbPalito_42.setSelected(false);

        } else {
            if (jbPalito_42.isSelected()) {
                nLinha = 4;
                nQtd++;
            } else {
                nQtd--;
                if (nQtd == 0) {
                    nLinha = 0;
                }
            }

        }

        System.out.println("Linha: " + nLinha + " " + "QTD: " + nQtd);

    }//GEN-LAST:event_jbPalito_42ActionPerformed

    private void jbPalito_43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPalito_43ActionPerformed

        if ((nQtd > 0) && (nLinha != 4)) {

            JOptionPane.showMessageDialog(null, "Apenas uma fileira de palitos pode ser mexida!");
            jbPalito_43.setSelected(false);

        } else {
            if (jbPalito_43.isSelected()) {
                nLinha = 4;
                nQtd++;
            } else {
                nQtd--;
                if (nQtd == 0) {
                    nLinha = 0;
                }
            }

        }

        System.out.println("Linha: " + nLinha + " " + "QTD: " + nQtd);

    }//GEN-LAST:event_jbPalito_43ActionPerformed

    private void jbPalito_44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPalito_44ActionPerformed

        if ((nQtd > 0) && (nLinha != 4)) {

            JOptionPane.showMessageDialog(null, "Apenas uma fileira de palitos pode ser mexida!");
            jbPalito_44.setSelected(false);

        } else {
            if (jbPalito_44.isSelected()) {
                nLinha = 4;
                nQtd++;
            } else {
                nQtd--;
                if (nQtd == 0) {
                    nLinha = 0;
                }
            }

        }

        System.out.println("Linha: " + nLinha + " " + "QTD: " + nQtd);

    }//GEN-LAST:event_jbPalito_44ActionPerformed

    private void jbPalito_45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPalito_45ActionPerformed

        if ((nQtd > 0) && (nLinha != 4)) {

            JOptionPane.showMessageDialog(null, "Apenas uma fileira de palitos pode ser mexida!");
            jbPalito_45.setSelected(false);

        } else {
            if (jbPalito_45.isSelected()) {
                nLinha = 4;
                nQtd++;
            } else {
                nQtd--;
                if (nQtd == 0) {
                    nLinha = 0;
                }
            }

        }

        System.out.println("Linha: " + nLinha + " " + "QTD: " + nQtd);

    }//GEN-LAST:event_jbPalito_45ActionPerformed

    private void jbPalito_46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPalito_46ActionPerformed

        if ((nQtd > 0) && (nLinha != 4)) {

            JOptionPane.showMessageDialog(null, "Apenas uma fileira de palitos pode ser mexida!");
            jbPalito_46.setSelected(false);

        } else {
            if (jbPalito_46.isSelected()) {
                nLinha = 4;
                nQtd++;
            } else {
                nQtd--;
                if (nQtd == 0) {
                    nLinha = 0;
                }
            }

        }

        System.out.println("Linha: " + nLinha + " " + "QTD: " + nQtd);

    }//GEN-LAST:event_jbPalito_46ActionPerformed

    private void jbPalito_47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPalito_47ActionPerformed

        if ((nQtd > 0) && (nLinha != 4)) {

            JOptionPane.showMessageDialog(null, "Apenas uma fileira de palitos pode ser mexida!");
            jbPalito_47.setSelected(false);

        } else {
            if (jbPalito_47.isSelected()) {
                nLinha = 4;
                nQtd++;
            } else {
                nQtd--;
                if (nQtd == 0) {
                    nLinha = 0;
                }
            }

        }

        System.out.println("Linha: " + nLinha + " " + "QTD: " + nQtd);

    }//GEN-LAST:event_jbPalito_47ActionPerformed

    private void jbPalito_48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPalito_48ActionPerformed

        if ((nQtd > 0) && (nLinha != 4)) {

            JOptionPane.showMessageDialog(null, "Apenas uma fileira de palitos pode ser mexida!");
            jbPalito_48.setSelected(false);

        } else {
            if (jbPalito_48.isSelected()) {
                nLinha = 4;
                nQtd++;
            } else {
                nQtd--;
                if (nQtd == 0) {
                    nLinha = 0;
                }
            }

        }

        System.out.println("Linha: " + nLinha + " " + "QTD: " + nQtd);

    }//GEN-LAST:event_jbPalito_48ActionPerformed

    private void jbPalito_49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPalito_49ActionPerformed

        if ((nQtd > 0) && (nLinha != 4)) {

            JOptionPane.showMessageDialog(null, "Apenas uma fileira de palitos pode ser mexida!");
            jbPalito_49.setSelected(false);

        } else {
            if (jbPalito_49.isSelected()) {
                nLinha = 4;
                nQtd++;
            } else {
                nQtd--;
                if (nQtd == 0) {
                    nLinha = 0;
                }
            }

        }

        System.out.println("Linha: " + nLinha + " " + "QTD: " + nQtd);

    }//GEN-LAST:event_jbPalito_49ActionPerformed

    private void jbPalito_51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPalito_51ActionPerformed

        if ((nQtd > 0) && (nLinha != 5)) {

            JOptionPane.showMessageDialog(null, "Apenas uma fileira de palitos pode ser mexida!");
            jbPalito_51.setSelected(false);

        } else {
            if (jbPalito_51.isSelected()) {
                nLinha = 5;
                nQtd++;
            } else {
                nQtd--;
                if (nQtd == 0) {
                    nLinha = 0;
                }
            }

        }

        System.out.println("Linha: " + nLinha + " " + "QTD: " + nQtd);

    }//GEN-LAST:event_jbPalito_51ActionPerformed

    private void jbPalito_52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPalito_52ActionPerformed

        if ((nQtd > 0) && (nLinha != 5)) {

            JOptionPane.showMessageDialog(null, "Apenas uma fileira de palitos pode ser mexida!");
            jbPalito_52.setSelected(false);

        } else {
            if (jbPalito_52.isSelected()) {
                nLinha = 5;
                nQtd++;
            } else {
                nQtd--;
                if (nQtd == 0) {
                    nLinha = 0;
                }
            }

        }

        System.out.println("Linha: " + nLinha + " " + "QTD: " + nQtd);

    }//GEN-LAST:event_jbPalito_52ActionPerformed

    private void jbPalito_53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPalito_53ActionPerformed

        if ((nQtd > 0) && (nLinha != 5)) {

            JOptionPane.showMessageDialog(null, "Apenas uma fileira de palitos pode ser mexida!");
            jbPalito_53.setSelected(false);

        } else {
            if (jbPalito_53.isSelected()) {
                nLinha = 5;
                nQtd++;
            } else {
                nQtd--;
                if (nQtd == 0) {
                    nLinha = 0;
                }
            }

        }

        System.out.println("Linha: " + nLinha + " " + "QTD: " + nQtd);

    }//GEN-LAST:event_jbPalito_53ActionPerformed

    private void jbPalito_54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPalito_54ActionPerformed

        if ((nQtd > 0) && (nLinha != 5)) {

            JOptionPane.showMessageDialog(null, "Apenas uma fileira de palitos pode ser mexida!");
            jbPalito_54.setSelected(false);

        } else {
            if (jbPalito_54.isSelected()) {
                nLinha = 5;
                nQtd++;
            } else {
                nQtd--;
                if (nQtd == 0) {
                    nLinha = 0;
                }
            }

        }

        System.out.println("Linha: " + nLinha + " " + "QTD: " + nQtd);

    }//GEN-LAST:event_jbPalito_54ActionPerformed

    private void jbPalito_55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPalito_55ActionPerformed

        if ((nQtd > 0) && (nLinha != 5)) {

            JOptionPane.showMessageDialog(null, "Apenas uma fileira de palitos pode ser mexida!");
            jbPalito_55.setSelected(false);

        } else {
            if (jbPalito_55.isSelected()) {
                nLinha = 5;
                nQtd++;
            } else {
                nQtd--;
                if (nQtd == 0) {
                    nLinha = 0;
                }
            }

        }

        System.out.println("Linha: " + nLinha + " " + "QTD: " + nQtd);

    }//GEN-LAST:event_jbPalito_55ActionPerformed

    private void jbPalito_56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPalito_56ActionPerformed

        if ((nQtd > 0) && (nLinha != 5)) {

            JOptionPane.showMessageDialog(null, "Apenas uma fileira de palitos pode ser mexida!");
            jbPalito_56.setSelected(false);

        } else {
            if (jbPalito_56.isSelected()) {
                nLinha = 5;
                nQtd++;
            } else {
                nQtd--;
                if (nQtd == 0) {
                    nLinha = 0;
                }
            }

        }

        System.out.println("Linha: " + nLinha + " " + "QTD: " + nQtd);

    }//GEN-LAST:event_jbPalito_56ActionPerformed

    private void jbPalito_57ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPalito_57ActionPerformed

        if ((nQtd > 0) && (nLinha != 5)) {

            JOptionPane.showMessageDialog(null, "Apenas uma fileira de palitos pode ser mexida!");
            jbPalito_57.setSelected(false);

        } else {
            if (jbPalito_57.isSelected()) {
                nLinha = 5;
                nQtd++;
            } else {
                nQtd--;
                if (nQtd == 0) {
                    nLinha = 0;
                }
            }

        }

        System.out.println("Linha: " + nLinha + " " + "QTD: " + nQtd);

    }//GEN-LAST:event_jbPalito_57ActionPerformed

    private void jbPalito_58ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPalito_58ActionPerformed

        if ((nQtd > 0) && (nLinha != 5)) {

            JOptionPane.showMessageDialog(null, "Apenas uma fileira de palitos pode ser mexida!");
            jbPalito_58.setSelected(false);

        } else {
            if (jbPalito_58.isSelected()) {
                nLinha = 5;
                nQtd++;
            } else {
                nQtd--;
                if (nQtd == 0) {
                    nLinha = 0;
                }
            }

        }

        System.out.println("Linha: " + nLinha + " " + "QTD: " + nQtd);

    }//GEN-LAST:event_jbPalito_58ActionPerformed

    private void jbPalito_59ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPalito_59ActionPerformed

        if ((nQtd > 0) && (nLinha != 5)) {

            JOptionPane.showMessageDialog(null, "Apenas uma fileira de palitos pode ser mexida!");
            jbPalito_59.setSelected(false);

        } else {
            if (jbPalito_59.isSelected()) {
                nLinha = 5;
                nQtd++;
            } else {
                nQtd--;
                if (nQtd == 0) {
                    nLinha = 0;
                }
            }
        }

        System.out.println("Linha: " + nLinha + " " + "QTD: " + nQtd);

    }//GEN-LAST:event_jbPalito_59ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Nim().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton jbConectar;
    private javax.swing.JButton jbEnviar;
    private javax.swing.JToggleButton jbPalito_11;
    private javax.swing.JToggleButton jbPalito_12;
    private javax.swing.JToggleButton jbPalito_13;
    private javax.swing.JToggleButton jbPalito_14;
    private javax.swing.JToggleButton jbPalito_15;
    private javax.swing.JToggleButton jbPalito_16;
    private javax.swing.JToggleButton jbPalito_17;
    private javax.swing.JToggleButton jbPalito_18;
    private javax.swing.JToggleButton jbPalito_19;
    private javax.swing.JToggleButton jbPalito_21;
    private javax.swing.JToggleButton jbPalito_22;
    private javax.swing.JToggleButton jbPalito_23;
    private javax.swing.JToggleButton jbPalito_24;
    private javax.swing.JToggleButton jbPalito_25;
    private javax.swing.JToggleButton jbPalito_26;
    private javax.swing.JToggleButton jbPalito_27;
    private javax.swing.JToggleButton jbPalito_28;
    private javax.swing.JToggleButton jbPalito_29;
    private javax.swing.JToggleButton jbPalito_31;
    private javax.swing.JToggleButton jbPalito_32;
    private javax.swing.JToggleButton jbPalito_33;
    private javax.swing.JToggleButton jbPalito_34;
    private javax.swing.JToggleButton jbPalito_35;
    private javax.swing.JToggleButton jbPalito_36;
    private javax.swing.JToggleButton jbPalito_37;
    private javax.swing.JToggleButton jbPalito_38;
    private javax.swing.JToggleButton jbPalito_39;
    private javax.swing.JToggleButton jbPalito_41;
    private javax.swing.JToggleButton jbPalito_42;
    private javax.swing.JToggleButton jbPalito_43;
    private javax.swing.JToggleButton jbPalito_44;
    private javax.swing.JToggleButton jbPalito_45;
    private javax.swing.JToggleButton jbPalito_46;
    private javax.swing.JToggleButton jbPalito_47;
    private javax.swing.JToggleButton jbPalito_48;
    private javax.swing.JToggleButton jbPalito_49;
    private javax.swing.JToggleButton jbPalito_51;
    private javax.swing.JToggleButton jbPalito_52;
    private javax.swing.JToggleButton jbPalito_53;
    private javax.swing.JToggleButton jbPalito_54;
    private javax.swing.JToggleButton jbPalito_55;
    private javax.swing.JToggleButton jbPalito_56;
    private javax.swing.JToggleButton jbPalito_57;
    private javax.swing.JToggleButton jbPalito_58;
    private javax.swing.JToggleButton jbPalito_59;
    private javax.swing.JLabel lbPalito_01;
    // End of variables declaration//GEN-END:variables
    public TCPClient tcpclient;
}
